PACKAGE_NAME="ipt_ISG"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="ipt_ISG"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
MAKE[0]="chmod +x configure && ./configure && make"
CLEAN="make clean"
POST_INSTALL="post_install.sh"
